language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/gsp-gen.sh -p gsp
- $HOME/build-script/travis-ci/build-nablarch.sh -p development
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: JMEjefdOQF3mhZu+PoIM0D+ycsqZhT27+bmoA3akVEdmj8ArTJMqAp6FrzHOhesUxqkatPUvJKodnfQPKu80cuySdAFEyFQ3P98qrowosCoCeN02nrDZY58mRXikAWRL0nw7txfOzCiKJTOoHtI6dPdiqhGzWooch0SEj2Tb6EJB8n5fLPVLwMiZroK9ZRUu6JP5BOvPZ+iaZ4YFwnJ/5o/Fxj7T6+KZ63evd+gja7fr4uW0jy55+c/5p73OXFZRfdPn1+lqC28Z1NanNhmkrxxNb8afQfBXAVHeAPXlKzIbqd7+2VSXOnCkTKTw0a0YSGW5yRR+efbs9SgEgBb61IWmdqyahd0fxf042BC9Q47QbnamjDYw01uO7U5OS/QJc64LJgc3lCP1mmhqnUaeB6+UQYPpIIbpDrEjPUJV+t1HotSKl+yL/xLZMmaN2HASgWalj17MLOJaJ/3J/3XLSyKueWasBn6ApHDfIp7bN2lbUnxMmCVflfNeUk81Gkmyvhk+v+2eIfYdxpV/8ZJnydTEZc2v86IVQwcTg+EtxihSXt6kBz64+NgSvut9RtFokQY1fFFx8vnFMiG9t9ohcJ/ng27UUD3MSt8iebpc2gV24roQNngdfIszrriuvYi79fXu6NLQ9LDbNBPaMnre5QAbSM5bHjvleHTvUKHK6pA=
